version: "3"

services:
  minio:
    restart: always
    image: quay.io/minio/minio:RELEASE.2022-10-08T20-11-00Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "miniouser"
      MINIO_ROOT_PASSWORD: "miniopassword"
    ports:
      - 9000:9000
      - 9001:9001

  minio-create-bucket:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./init_bucket.sh:/tmp/init_bucket.sh:ro
      - ./upload_dataset.sh:/tmp/upload_dataset.sh:ro
    depends_on:
      - minio
    environment:
      S3_ENDPOINT: http://minio:9000
      S3_USER: miniouser
      S3_PASSWORD: miniopassword
      S3_BUCKET: mlsystemdesign22
    entrypoint: >
      /bin/sh -c "
          /bin/sh /tmp/init_bucket.sh
          /bin/sh /tmp/upload_dataset.sh
          exit 0;
      "
