version: "3"

services:
  k3s-server:
    restart: always
    image: "rancher/k3s:v1.25.3-k3s1"
    command: server
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    environment:
      - K3S_TOKEN=1668278241204
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - ./kubeconfig.yaml:/output/kubeconfig.yaml
      - k3s-server:/var/lib/rancher/k3s
    ports:
      - "6443:6443"
      - "80:80"
      - "443:443"
    networks:
      - mlsystemdesign22net

  k3s-agent:
    image: "rancher/k3s:v1.25.3-k3s1"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_URL=https://k3s-server:6443
      - K3S_TOKEN=1668278241204
    networks:
      - mlsystemdesign22net

  redis:
    restart: always
    image: redis:7.0.5
    ports:
      - "6379:6379"
    networks:
      - mlsystemdesign22net
    logging:
      options:
        max-size: 10m

  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mlsystemdesign22net
    logging:
      options:
        max-size: 10m

volumes:
  k3s-server:
  pgdata:

networks:
  mlsystemdesign22net:
