replicas: 1
updateStrategy: RollingUpdate
restartPolicy: 'Always'
imagePullSecrets:
  secretName:
image:
  registry:
  repository: receiver
  tag: latest
imagePullPolicy: 'Always'


integrations:
  s3:
    endpointUrl: ''
    accessKey: ''
    secretKey: ''
    bucket: ''
    pathPrefix: ''
    feedbackPathPrefix: ''
    verify: false
  telegram:
    token: ''
  redis:
    host: ''
    port: ''
    queue: ''
    username: ''
    password: ''
