apiVersion: v1
kind: Service
metadata:
  name: predictor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/port: "8000"
    prometheus.io/path: "/prometheus"
spec:
  selector:
    app: predictor
  ports:
    - name: predictor
      protocol: TCP
      port: 8000
      targetPort: 8000
