apiVersion: v1
kind: Service
metadata:
  name: receiver
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/port: "8001"
    prometheus.io/path: "/prometheus"
spec:
  selector:
    app: receiver
  ports:
    - name: receiver
      protocol: TCP
      port: 8001
      targetPort: 8001
