replicas: 1
updateStrategy: RollingUpdate
restartPolicy: 'Always'
imagePullSecrets:
  secretName: ''
image:
  registry: 'markandreev/'
  repository: 'predictor'
  tag: '20221209-3'
imagePullPolicy: 'IfNotPresent'

model:
  name: ''
  stage: ''

integrations:
  mlflow:
    trackingUrl: ''
  s3:
    endpointUrl: ''
    accessKey: ''
    secretKey: ''
    bucket: ''
    pathPrefix: ''
    verify: false
  telegram:
    token: ''
  redis:
    host: ''
    port: ''
    queue: ''
    username: ''
    password: ''
