version: "3"

services:
  minio:
    restart: always
    image: quay.io/minio/minio:RELEASE.2022-10-08T20-11-00Z
    command: server /data --console-address ":9001"
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: "miniouser"
      MINIO_ROOT_PASSWORD: "miniopassword"
    networks:
      - mlsystemdesign22net
    ports:
      - "9000:9000"
      - "9001:9001"

  minio-init-bucket:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: init_bucket/
    volumes:
      - minio-init-bucket:/opt/minio-init-bucket
    networks:
      - mlsystemdesign22net
    depends_on:
      - minio
    environment:
      S3_ENDPOINT: "http://minio:9000"
      S3_USER: "miniouser"
      S3_PASSWORD: "miniopassword"
      S3_BUCKET: "mlsystemdesign22"

  mlflow:
    restart: always
    build:
      context: mlflow
      dockerfile: Dockerfile
    networks:
      - mlsystemdesign22net
    ports:
      - "5500:5500"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: miniouser
      AWS_SECRET_ACCESS_KEY: miniopassword
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: mlflow-db
      DB_PORT: 5432
      DB_NAME: postgres
      S3_BUCKET: mlsystemdesign22
      S3_BUCKET_PREFIX: mlflow

  mlflow-db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - mlsystemdesign22net
    logging:
      options:
        max-size: 10m

  airflow:
    build:
      dockerfile: Dockerfile
      context: airflow
    restart: always
    networks:
      - mlsystemdesign22net
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "1"
    command: airflow standalone

  registry:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    networks:
      - mlsystemdesign22net


volumes:
  minio-storage:
  minio-init-bucket:

networks:
  mlsystemdesign22net:
